var INTRO = ["", "", "",
	"<p>Les caractéristiques peuvent être déterminées de deux manières :</p><p>1) Répartition de 27 points suivant le barème des règles (max 15 pour une caractéristique). Le nombre de points consommés est indiqué en bas. Une répartition typique est :</p><h3>15 - 14 - 13 - 12 - 10 - 8</h3><p>ou</p><p>2) Tirez 6 fois 4d6, gardez les 3 meilleurs d6 à chaque fois, et reportez les scores dans l'ordre de votre choix. Votre tirage donne :</p>",
	"",
	"",
	"",
	"<p>Les points de vie (pv) peuvent être déterminés de deux manières :</p><p>1) pv max au niveau 1 puis moyenne arrondie au supérieur à chaque niveau suivant.</p><p>ou</p><p>2) pv max au niveau 1 puis lancez un DV à chaque niveau suivant.</p>",
	"<h4>Étiquettes des sorts</h4><p><strong>(ext)</strong> Liste de sorts étendue définie dans le <em>Player's Handbook</em> pour cette classe.</p><p><strong>[TCoE]</strong> Liste de sorts étendue proposée dans le supplément <em>Tasha's Cauldron of Everything</em>. Ne choisissez ces sorts que si votre MD autorise cette règle optionelle.</p>",
	"<p>L'équipement pré-sélectionné n'est qu'un exemple donné par les règles pour un niveau 1. Vous pouvez le modifier.</p><p>Consultez votre MD pour savoir combien de pièces d'or vous pouvez dépenser suivant le niveau de votre personnage.</p>",
	"",
	"<p><i class='fas fa-download bFinalize' onclick=\"location='export.php'\"></i>Réaliser une sauvegarde locale de votre personnage au format .xml pour vous permettre de reprendre la fiche plus tard pour faire évoluer votre personnage.</p><hr />	<p><i class='fas fa-file-alt bFinalize' onclick=\"window.open('sheetPrint.php?cb', '_blank')\"></i>Générer la feuille de personnage \"papier\", prête pour l'impression (activez 'Graphiques d'arrière-plan' sur votre navigateur) ou pour la sauvegarder en PDF. Vous pouvez éditer manuellement les champs.</p><hr />	<p><i class='fas fa-address-card bFinalize' onclick=\"window.open('sheetScreen.php?new', '_blank')\"></i>Générer une feuille de personnage en ligne sauvegardée sur notre serveur et consultable d'où vous voulez. Vous pouvez éditer manuellement les champs.<br /><em>Vous devez être connecté au forum d'AideDD pour avoir accès à cette fonctionnalité.</em></p><hr />	<p><i class='fas fa-file-code bFinalize' onclick=\"ClipBoard()\"></i>Générer la feuille de personnage au format BBCode (pop-up) pour pouvoir la copier/coller directement sur un forum.</p>"
];

var TRAITS = [	[ 	/* Acolyte */
					"J'idolâtre un héros particulier de ma foi, et renvoie constamment à ses actes et à son exemple.",
					"Je peux trouver un terrain d'entente entre les ennemis les plus féroces, ressentir de l'empathie pour eux et toujours travailler vers la paix.",
					"Je vois des présages dans chaque événement et action. Les dieux essaient de nous parler, nous avons juste besoin d'écouter.",
					"J'ai toujours une attitude optimiste.",
					"Je cite (ou paraphrase) des textes sacrés et des proverbes dans presque toutes les situations.",
					"Je suis tolérant (ou intolérant) vis-à-vis des autres fois et je respecte (ou condamne) l'adoration des autres dieux.",
					"J'ai apprécié la bonne nourriture, les boissons et la haute société parmi l'élite de mon temple. La vie rude me fait grincer.",
					"J'ai passé tellement de temps dans mon temple que j'ai peu d'expérience pratique pour traiter avec les gens du monde extérieur." ],
				[	/* Artiste */
					"Je connais une histoire en rapport avec chaque situation.",
					"À chaque fois que j'arrive dans un nouvel endroit, je m'entiche des rumeurs locales et répands les commérages.",
					"Je suis désespérément romantique, toujours à la recherche de cette 'personne spéciale'.",
					"Personne ne reste en colère contre moi très longtemps, car je peux désamorcer toute tension.",
					"J'adore les bonnes insultes, même celles qui sont dirigées contre moi.",
					"Je deviens acerbe si je ne suis pas le centre de l'attention.",
					"Je ne peux me contenter que de la perfection.",
					"Je change mon humeur ou mon état d'esprit aussi vite que je change de note dans une chanson." ],
				[	/* Artisan */
					"Je crois que si quelque chose doit être fait, il doit l'être correctement. Je n'y peux rien, je suis un perfectionniste.",
					"Je suis un snob qui regarde de haut ceux qui ne peuvent apprécier les arts de qualité.",
					"Je veux tout le temps savoir comment les choses fonctionnent et ce qui pousse les gens à avancer.",
					"Je lance plein d'aphorismes spirituels et ai un proverbe pour chaque occasion.",
					"Je suis grossier envers ceux qui n'ont pas mon engagement pour le travail bien fait et mon fair-play.",
					"J'aime parler de longues heures de ma profession.",
					"Je ne me sépare pas de mon or facilement et marchande sans relâche pour faire la meilleure affaire possible.",
					"Je suis reconnu pour mon travail, et je veux m'assurer que tout le monde l'apprécie. Je suis toujours pris au dépourvu lorsque quelqu'un n'a pas entendu parlé de moi." ],
				[	/* Charlatan */
					"Je tombe facilement amoureux, mais passe rapidement à une autre personne. Je suis toujours en train de faire la cour à quelqu'un.",
					"J'ai une blague pour n'importe quelle occasion, en particulier pour les situations où l'humour n'est pas approprié.",
					"La flatterie est mon astuce préférée pour obtenir ce que je veux.",
					"Je suis un joueur né qui ne peut s'empêcher de prendre des risques pour un gain potentiel.",
					"Je mens sur à peu près tout, même s'il n'y a aucune bonne raison pour le faire.",
					"Les sarcasmes et les insultes sont mes armes favorites.",
					"Je conserve tout un tas de symboles sacrés sur moi et prie toute divinité qui pourrait me venir en aide à un moment.",
					"Je mets dans mes poches tout ce que je vois et qui pourrait avoir une quelconque valeur." ],
				[	/* Criminel */
					"J'ai toujours un plan pour savoir quoi faire quand les choses vont mal.",
					"Je suis toujours calme, quelle que soit la situation. Je n'élève pas la voix ou ne laisse pas mes émotions me contrôler.",
					"La première chose que je fais dans un nouveau lieu est de noter les emplacements de toute chose précieuse, ou bien là où ces choses pourraient être cachées.",
					"Je préfère me faire un nouvel ami qu'un nouvel ennemi.",
					"Je suis incroyablement lent à faire confiance. Ceux qui semblent les plus droits sont souvent ceux qui ont le plus à cacher.",
					"Je ne fais pas attention aux risques d'une situation.",
					"La meilleure façon de me faire faire quelque chose est de me dire de ne pas le faire.",
					"J'explose à la moindre insulte." ],
				[	/* ermite */
					"J'ai été isolé pendant tellement longtemps que je ne parle que rarement, préférant les gestes et quelques grognements occasionnels.",
					"Je suis toujours serein, même confronté à un désastre.",
					"Le chef de ma communauté avait de sages paroles pour tout sujet, et je suis désireux de partager cette sagesse.",
					"Je ressens une immense empathie pour tous ceux qui souffrent.",
					"Je suis insensible à l'étiquette et aux attentes sociales.",
					"Je relie tout ce qui m'arrive à une grande machination cosmique.",
					"Je me perds souvent dans mes pensées et dans la contemplation, ce qui me rend insensible à mon entourage.",
					"Je travaille sur une grande théorie philosophique et j'aime transmettre mes idées." ],
				[ 	/* sauvageon */
					"J'éprouve le besoin de voir le monde, c'est ce qui m'a fait quitter mon foyer.",
					"Je garde un œil sur mes amis, comme s'ils étaient les langes d'un nouveau-né.",
					"J'ai couru une fois sur 40 kilomètres sans m'arrêter pour prévenir mon clan de l'approche d'une horde d'orcs. Je le referai s'il le faut.",
					"J'ai une leçon pour chaque situation, leçon que j'ai découverte en observant la nature.",
					"Je n'accorde pas d'importance aux riches ou aux gens bien-élevés. L'argent ou les bonnes manières ne sauveront personne face à un ours-hibou affamé.",
					"Je ramasse toujours ce qui traîne, jouant distraitement avec, et parfois les cassant accidentellement.",
					"Je me sens bien plus dans mon élément entouré d'animaux que de personnes.",
					"J'ai, en fait, été élevé par des loups." ],
				[	/* enfant des rues */
					"Je cache des restes de nourriture et des babioles dans mes poches.",
					"Je pose beaucoup de questions.",
					"J'aime me glisser dans des espaces étroits, là où personne ne peut m'atteindre.",
					"Je dors le dos contre un mur ou un arbre, avec tout ce que je possède empaqueté entre mes bras.",
					"Je mange comme un cochon et j'ai de mauvaises manières.",
					"Je pense que tous ceux qui sont gentils avec moi ont en réalité une mauvaise intention.",
					"Je n'aime pas me laver.",
					"Je dis crûment ce que les autres insinuent ou cachent." ],
				[	/* heros du peuple */
					"Je juge les gens sur leurs actions, pas sur leurs paroles.",
					"Si quelqu'un est en difficulté, je suis toujours prêt à lui apporter de l'aide.",
					"Quand je me fixe sur quelque chose, je fonce, peu importe ce qui sera sur ma route.",
					"J'ai un fort sentiment de justice et j'essaye toujours de trouver la solution la plus équitable aux différends.",
					"J'ai confiance en mes capacités et je fais ce que je peux pour inspirer la confiance aux autres.",
					"La pensée est pour les autres. Moi je préfère l'action.",
					"J'utilise mal les mots longs lorsque j'essaye de paraître intelligent.",
					"Je m'ennuie facilement. Quand vais-je suivre mon destin ?" ],
				[	/* marin */
					"Mes amis savent qu'ils peuvent compter sur moi, quoi qu'il arrive.",
					"Je travaille dur donc je peux me lâcher totalement lorsque le travail est terminé.",
					"J'aime naviguer vers de nouveaux ports et me faire de nouveaux amis autour d'une choppe de bière.",
					"J'altère un peu les faits pour créer une bonne histoire.",
					"Pour moi, une taverne bruyante est le meilleur moyen d'apprendre à connaître une ville.",
					"Je ne laisse jamais passer un pari amical.",
					"Mon langage est aussi pourri qu'un nid d'otyugh.",
					"J'aime le travail bien fait, en particulier si je peux convaincre quelqu'un d'autre de le faire à ma place." ],
				[	/* noble */
					"Ma flatterie éloquente fait sentir à toute personne à qui je parle qu'elle est la plus merveilleuse et la plus importante au monde.",
					"Les gens ordinaires m'aiment pour ma gentillesse et ma générosité.",
					"Nul ne peut douter en regardant mon allure royale que je suis un cran au-dessus des masses de bouseux.",
					"Je prends grand soin de toujours m'habiller de mon mieux et de suivre les dernières tendances.",
					"Je n'aime pas me salir les mains, et je ne veux pas finir dans des logements inappropriés.",
					"Malgré ma noble naissance, je ne me place pas au-dessus des autres. Nous avons tous le même sang.",
					"Mon soutien, une fois perdu, est perdu à jamais.",
					"Si vous me blessez, je vais vous écraser, souiller votre nom et ruiner vos champs." ],
				[	/* sage */
					"J'utilise de grands mots qui donnent l'impression d'une grande érudition.",
					"J'ai lu tous les livres des plus grandes bibliothèques du monde, ou du moins je me vante de l'avoir fait.",
					"Je suis habitué à aider ceux qui ne sont pas aussi intelligents que moi, et j'explique patiemment tout et n'importe quoi aux autres.",
					"Il n'y a rien que j'aime plus au monde qu'un bon mystère.",
					"Je suis disposé à écouter tous les arguments avant de me faire mon propre jugement.",
					"Je... parle... lentement... quand je parle... à des idiots... soit... presque... à tout le monde... si je... compare... avec moi.",
					"Je suis horriblement et terriblement maladroit dans les situations sociales.",
					"Je suis convaincu que les gens sont toujours en train d'essayer de me voler mes secrets." ],
				[	/* soldat */
					"Je suis toujours poli et respectueux.",
					"Je suis hanté par les souvenirs de la guerre. Je ne peux pas sortir les images de violence de ma tête.",
					"J'ai perdu beaucoup d'amis, et je suis lent à m'en faire de nouveaux.",
					"Je connais plein d'histoires inspirantes et effrayantes de mon expérience militaire qui se révèlent pertinentes dans de nombreuses situations de combat.",
					"Je peux faire baisser le regard d'un chien des enfers sans broncher.",
					"J'aime être fort et casser des choses.",
					"J'ai un sens de l'humour brut.",
					"J'affronte les problèmes de front. Une solution simple et directe est le meilleur chemin vers le succès." ],
				[	/* chevalier */
					"Ma flatterie éloquente fait sentir à toute personne à qui je parle qu'elle est la plus merveilleuse et la plus importante au monde.",
					"Les gens ordinaires m'aiment pour ma gentillesse et ma générosité.",
					"Nul ne peut douter en regardant mon allure royale que je suis un cran au-dessus des masses de bouseux.",
					"Je prends grand soin de toujours m'habiller de mon mieux et de suivre les dernières tendances.",
					"Je n'aime pas me salir les mains, et je ne veux pas finir dans des logements inappropriés.",
					"Malgré ma noble naissance, je ne me place pas au-dessus des autres. Nous avons tous le même sang.",
					"Mon soutien, une fois perdu, est perdu à jamais.",
					"Si vous me blessez, je vais vous écraser, souiller votre nom et ruiner vos champs." ],
				[	/* voyageur */
					"J'ai toujours une anecdote de voyage à raconter à propos de n'importe quelle situation.",
					"J'ai vu tellement de choses que plus rien ne me surprend vraiment.",
					"Je suis toujours prêt à accorder le bénéfice du doute à une créature et ne me fie jamais à mes préjugés.",
					"Je ne tiens pas en place et je m'ennuie si je passe plus de quelques jours au même endroit.",
					"Je suis persuadé que je porte la guigne aux personnes autour de moi, aussi je ne reste jamais longtemps quelque part.",
					"J'aime voyager seul et même lorsque je suis dans un groupe j'entreprends parfois des escapades en solitaire.",
					"Je suis fasciné par tout ce qui me semble exotique, objets, créatures ou personnes.",
					"Je suis condescendant envers les bouseux qui ne sont jamais sortis de leur village." ],
				[	/* captif */
					"De temps en temps un comportement bestial m'envahi et je perds les bonnes manières.",
					"Je fais encore souvent des cauchemars la nuit.",
					"La seule mention du nom de ces créatures me perturbe.",
					"Je vois maintenant souvent une situation sous un angle différent des autres.",
					"J'ai perdu des années précieuses de mon existence et je veux toujours aller vite maintenant.",
					"Je ne supporte pas l'idée de faire vivre à quelle créature que ce soit ce que j'ai enduré.",
					"J'ai horreur de dire à quelqu'un ce qu'il doit faire.",
					"J'ai des traces visibles des maltraitances que j'ai subies." ],
				[	/* idiot */
					"Je dis toujours l'inverse de ce que je pense. C'est une très mauvaise habitude.",
					"Je cherche toujours à me mettre dans une position où je peux espionner les autres et écouter leurs conversations.",
					"Je passe mon temps à prophétiser des désastres ou des cataclysmes (imaginaires ou réels) et personne ne me croit jamais.",
					"J'ai des moments d'absences de conscience. Mon regard se vide et la bave coule sur mon menton.",
					"Je n'ai aucune conscience de la hiérarchie, de l'étiquette et des attentes sociales.",
					"J'aime les gens et veux toujours faire des câlins à tout le monde.",
					"J'ai un vocabulaire très limité, ce qui m'oblige à remplacer des mots que je ne connais pas par « truc » ou « machin », rendant la plupart de mes phrases incompréhensibles.",
					"Je me déplace en sautillant d'une façon totalement ridicule." ],
				[	/* chasseur urbain */
					"J'ai toujours un plan pour savoir quoi faire quand les choses vont mal.",
					"Je suis toujours calme, quelle que soit la situation. Je n'élève pas la voix ou ne laisse pas mes émotions me contrôler.",
					"La première chose que je fais dans un nouveau lieu est de noter les emplacements de toute chose précieuse, ou bien là où ces choses pourraient être cachées.",
					"Je préfère me faire un nouvel ami qu'un nouvel ennemi.",
					"Je suis incroyablement lent à faire confiance. Ceux qui semblent les plus droits sont souvent ceux qui ont le plus à cacher.",
					"Je ne fais pas attention aux risques d'une situation.",
					"La meilleure façon de me faire faire quelque chose est de me dire de ne pas le faire.",
					"J'explose à la moindre insulte." ],
				[	/* vétéran */
					"Je suis toujours poli et respectueux.",
					"Je suis hanté par les souvenirs de la guerre. Je ne peux pas sortir les images de violence de ma tête.",
					"J'ai perdu beaucoup d'amis, et je suis lent à m'en faire de nouveaux.",
					"Je connais plein d'histoires inspirantes et effrayantes de mon expérience militaire qui se révèlent pertinentes dans de nombreuses situations de combat.",
					"Je peux faire baisser le regard d'un chien des enfers sans broncher.",
					"J'aime être fort et casser des choses.",
					"J'ai un sens de l'humour brut.",
					"J'affronte les problèmes de front. Une solution simple et directe est le meilleur chemin vers le succès." ],
];

var IDEAUX = [	[ 	/* Acolyte */
					"Tradition. Les anciennes traditions de culte et de sacrifice doivent être préservées et respectées (Loyal).",
					"Charité. J'essaie toujours d'aider ceux dans le besoin, quel qu'en soit le coût (Bon).",
					"Progrès. Nous devons aider à mettre en place sur terre les changements que les dieux réalisent constamment (Chaotique).",
					"Pouvoir. J'espère un jour parvenir au sommet de la hiérarchie religieuse de ma foi (Loyal).",
					"Foi. J'ai confiance dans le fait que ma divinité guidera mes actions et que si je travaille dur, tout ira bien (Loyal).",
					"Aspiration. Je cherche à me montrer digne de la faveur de mon dieu en faisant correspondre mes actions avec ses enseignements (tout alignement)." ],
				[	/* Artiste */
					"Beauté. Lorsque je fais une représentation, je rends le monde meilleur qu'il ne l'était (Bon).",
					"Tradition. Les histoires, les légendes et les chansons du passé ne devraient jamais être oubliées, car elles nous apprennent qui nous sommes (Loyal).",
					"Créativité. Le monde a besoin de nouvelles idées et d'audace (Chaotique).",
					"Avarice. Je ne fais cela que pour l'or et la gloire (Mauvais).",
					"Peuple. J'aime voir des sourires sur les visages qui m'entourent lorsque je fais ma représentation. C'est tout ce qui m'importe (Neutre).",
					"Honnêteté. L'art doit être le reflet de l'âme ; il doit provenir du plus profond de notre être et révéler qui nous sommes (Tout alignement)." ],
				[	/* Artisan */
					"Communauté. Il est du devoir de tout peuple civilisé de renforcer les liens qui unissent sa communauté ainsi que d'assurer la sécurité de sa civilisation (Loyal).",
					"Générosité. Mes talents m'ont été donnés pour que je les utilise pour le plus grand nombre (Bon).",
					"Liberté. Chacun devrait être libre d'exercer son propre gagne-pain (Chaotique).",
					"Avarice. Je ne suis là que pour l'argent (Mauvais).",
					"Peuple. Je m'engage pour des personnes que j'apprécie, pas pour des idées (Neutre).",
					"Aspiration. Je travaille dur pour être le meilleur dans mon domaine (Tout alignement)." ],
				[	/* Charlatan */
					"Indépendance. Je suis un esprit libre, personne ne me dit ce que je dois faire (Chaotique).",
					"Justice. Je ne cible jamais une personne qui ne peut pas se permettre de perdre quelques pièces (Loyal).",
					"Charité. Je distribue l'argent que j'obtiens à ceux qui en ont vraiment besoin (Bon).",
					"Créativité. Je ne fais jamais deux fois la même arnaque (Chaotique).",
					"Amitié. Les biens matériels vont et viennent. Les liens d'amitié qui se tissent durent éternellement (Bon).",
					"Aspiration. Je suis déterminé à faire quelque chose de ma vie (Tout alignement)." ],
				[	/* Criminel */
					"Honneur. Je ne vole pas les autres dans une négociation (Loyal).",
					"Liberté. Les chaînes sont faites pour être brisées, de même que ceux qui les forgent (Chaotique).",
					"Charité. Je vole des riches pour pouvoir aider ceux qui sont dans le besoin (Bon).",
					"Avidité. Je ferai tout ce qu'il faut pour devenir riche (Mauvais).",
					"Personnes. Je suis fidèle à mes amis, pas à des idéaux, et tous les autres peuvent bien s'embarquer sur le Styx, ça ne m'importe pas (Neutre).",
					"Rédemption. Il y a une étincelle de bonté en chacun de nous (Bon)." ],
				[	/* ermite */
					"Bien commun. Mes dons sont destinés à être partagés par tous, et non pour mon propre intérêt (Bon).",
					"Logique. Les émotions ne doivent pas brouiller notre sens de ce qui est vrai et faux, ou notre pensée logique (Loyal).",
					"Libre pensée. L'investigation et la curiosité sont les piliers du progrès (Chaotique).",
					"Pouvoir. La solitude et la contemplation sont des voies vers le pouvoir mystique ou magique (Mauvais).",
					"Vivre et laisser vivre. Se mêler des affaires des autres n'apporte que des problèmes (Neutre).",
					"Connaissance de soi. Si vous vous connaissez, il n'y a plus rien à savoir (Tout alignement)." ],
				[ 	/* sauvageon */
					"Changement. La vie est comme les saisons, en changement constant, et nous devons changer avec elle (Chaotique).",
					"Le plus grand bien. Il est de la responsabilité de chacun de faire ce qu'il y a de mieux pour l'ensemble de la tribu (Bon).",
					"Honneur. Si je me déshonore, je déshonore l'ensemble de ma tribu (Loyal).",
					"Puissance. Les plus forts sont destinés à gouverner (Mauvais).",
					"Nature. Le monde naturel est bien plus important que toutes les constructions des peuples civilisés (Neutre).",
					"Gloire. Je dois gagner la gloire lors de batailles, pour moi même et pour mon clan (Tout alignement)." ],
				[	/* enfant des rues */
					"Respect. Tout le monde, pauvre ou riche, mérite d'être respecté (Bon).",
					"Communauté. Nous devons prendre soin les uns des autres, parce que personne d'autre ne le fera (Loyal).",
					"Changement. Les faibles doivent s'élever, et les élites et les puissants doivent être mis à terre. Le changement est dans la nature des choses (Chaotique).",
					"Châtiment Les riches ont besoin qu'on leur montre que la vie et la mort ne font pas de différence avec ceux qui vivent dans le caniveau (Mauvais).",
					"Peuple. J'aide ceux qui m'aident, c'est ce qui nous permet de rester en vie (Neutre).",
					"Aspiration. Je vais leur montrer que je mérite une vie meilleure (Tout alignement)." ],
				[	/* heros du peuple */
					"Respect. Les gens méritent d'être traités avec dignité et respect (Bon).",
					"Équité. Personne ne devrait obtenir un traitement préférentiel devant la loi, et nul n'est au-dessus de la loi (Loyal).",
					"Liberté. On ne doit pas permettre aux tyrans d'opprimer le peuple (Chaotique).",
					"Puissance. Si je deviens fort, je peux prendre ce que je veux, ce que je mérite (Mauvais).",
					"Sincérité. Il n'est pas bon de faire semblant d'être ce que l'on n'est pas (Neutre).",
					"Destin. Rien ni personne ne peut me détourner de mon destin (Tout alignement)." ],
				[	/* marin */
					"Respect. Ce qui maintient l'unité sur un navire est le respect mutuel qu'il y a entre le capitaine et son équipage (Bon).",
					"Justice. Nous faisons tous notre travail, nous avons donc tous notre part de récompense (Loyal).",
					"Liberté. La mer c'est la liberté, la liberté d'aller partout et de faire ce que l'on veut (Chaotique).",
					"Domination. Je suis un prédateur, et les autres bateaux sur la mer sont mes proies (Mauvais).",
					"Peuple. Je m'engage pour mes coéquipiers, pas pour des idéaux (Neutre).",
					"Aspiration. Un jour j'aurai mon propre navire et suivrai ma propre destiné (Tout alignement)." ],
				[	/* noble */
					"Respect. Le respect m'est dû de par ma position, mais toutes les personnes, quelle que soit leur position, méritent d'être traitées avec dignité (Bon).",
					"Responsabilité. Il est de mon devoir de respecter l'autorité de ceux qui sont au-dessus de moi, tout comme ceux qui sont en-dessous doivent me respecter (Loyal).",
					"Indépendance. Je dois prouver que je peux me débrouiller sans le cocon de ma famille (Chaotique).",
					"Pouvoir. Si je peux obtenir plus de pouvoir, on ne me dira plus ce qu'il faut faire (Mauvais).",
					"Famille. Le sang est plus épais que l'eau (Tout alignement).",
					"Obligation de noble. Il est de mon devoir de protéger et de soigner les gens au-dessous moi (Bon)." ],
				[	/* sage */
					"Connaissances. Le chemin vers le pouvoir et le progrès personnel passe par la connaissance (Neutre).",
					"Beauté. Ce qui est beau nous montre au-delà de cela ce qui est vrai (Bon).",
					"Logique. Les émotions ne doivent pas obscurcir notre pensée logique (Loyal).",
					"Sans limites. Rien ne doit entraver les infinies possibilités inhérentes à toute existence (Chaotique).",
					"Pouvoir. La connaissance est la voie vers le pouvoir et la domination (Mauvais).",
					"Progrès personnel. Le but d'une vie d'étude est l'amélioration de soi-même (Tout alignement)." ],
				[	/* soldat */
					"Bonté. Notre sort est de donner notre vie pour la défense des autres (Bon).",
					"Responsabilité. Je fais ce que je dois faire et j'obéis aux autorités quand elles sont justes (Loyal).",
					"Indépendance. Quand les gens suivent les ordres aveuglément, ils embrassent une sorte de tyrannie (Chaotique).",
					"Puissance. Dans la vie comme à la guerre, le plus fort gagne (Mauvais).",
					"Vivre et laisser vivre. Les idéaux ne méritent pas qu'on tue ou qu'on fasse la guerre pour eux (Neutre).",
					"Nation. Ma ville, mon pays ou les miens sont tout ce qui importe (Tout alignement)." ],
				[	/* chevalier */
					"Respect. Le respect m'est dû de par ma position, mais toutes les personnes, quelle que soit leur position, méritent d'être traitées avec dignité (Bon).",
					"Responsabilité. Il est de mon devoir de respecter l'autorité de ceux qui sont au-dessus de moi, tout comme ceux qui sont en-dessous doivent me respecter (Loyal).",
					"Indépendance. Je dois prouver que je peux me débrouiller sans le cocon de ma famille (Chaotique).",
					"Pouvoir. Si je peux obtenir plus de pouvoir, on ne me dira plus ce qu'il faut faire (Mauvais).",
					"Famille. Le sang est plus épais que l'eau (Tout alignement).",
					"Obligation de noble. Il est de mon devoir de protéger et de soigner les gens au-dessous moi (Bon)." ],
				[	/* voyageur */
					"Le monde est plein de merveilles et je veux toutes les voir (Bon).",
					"Pourquoi rester toute sa vie dans un endroit quand on peut prendre la route (Chaotique).",
					"Il est de mon devoir de comprendre les autres peuples et d'aller à leur rencontre (Loyal).",
					"Chaque peuple a des façons différentes de faire souffrir, un jour, je les connaîtrai toutes (Mauvais).",
					"Le monde est vaste, peut-être n'ai-je pas encore tout vu ? (Tous).",
					"La route est mon seul vrai ami (Neutre)." ],
				[	/* captif */
					"L'esclavage est un fléau qui doit être combattu sous toutes ses formes (Bon).",
					"La liberté est le plus cher des privilèges (Chaotique).",
					"Œil pour œil, dent pour dent (Mauvais).",
					"Vivre sans loi c'est vivre sans règle (Loyal).",
					"Tout est question d'équilibre, ne jugez pas sans savoir (Neutre).",
					"Tout être vivant a des droits et des devoirs (Tout alignement)." ],
				[	/* idiot */
					"Liberté. La seule chose importante dans la vie est de faire ce que l'on veut quand on le veut (Chaotique).",
					"Humour. Le rire est ce qu'il y a de plus puissant et il est nécessaire de le répandre (Bon).",
					"Rédemption. Il y a une étincelle de bonté en chacun de nous (Bon).",
					"Personnes. Je suis fidèle à mes amis et aux personnes qui sont bonnes à mon égard. Les autres n'ont aucune importance à mes yeux (Neutre).",
					"Cruauté. Il n'y a pas de plus grand plaisir que de faire souffrir les autres (Mauvais).",
					"Découverte de soi. Trouver un sens à son existence est l'accomplissement ultime (Tout Alignement)." ],
				[	/* chasseur urbain */
					"Honneur. Je ne vole pas les autres dans une négociation (Loyal).",
					"Liberté. Les chaînes sont faites pour être brisées, de même que ceux qui les forgent (Chaotique).",
					"Charité. Je vole des riches pour pouvoir aider ceux qui sont dans le besoin (Bon).",
					"Avidité. Je ferai tout ce qu'il faut pour devenir riche (Mauvais).",
					"Personnes. Je suis fidèle à mes amis, pas à des idéaux, et tous les autres peuvent bien s'embarquer sur le Styx, ça ne m'importe pas (Neutre).",
					"Rédemption. Il y a une étincelle de bonté en chacun de nous (Bon)." ],
				[	/* vétéran */
					"Bonté. Notre sort est de donner notre vie pour la défense des autres (Bon).",
					"Responsabilité. Je fais ce que je dois faire et j'obéis aux autorités quand elles sont justes (Loyal).",
					"Indépendance. Quand les gens suivent les ordres aveuglément, ils embrassent une sorte de tyrannie (Chaotique).",
					"Puissance. Dans la vie comme à la guerre, le plus fort gagne (Mauvais).",
					"Vivre et laisser vivre. Les idéaux ne méritent pas qu'on tue ou qu'on fasse la guerre pour eux (Neutre).",
					"Nation. Ma ville, mon pays ou les miens sont tout ce qui importe (Tout alignement)." ],
];

var LIENS = [	[ 	/* Acolyte */
					"Je cherche une ancienne relique de ma foi qui a été perdue il y a longtemps. Je mourrais pour la récupérer.",
					"Un jour je me vengerai de la hiérarchie corrompue de ce temple qui m'a accusé d'être un hérétique.",
					"Je dois ma vie au prêtre qui m'a recueilli quand mes parents sont morts.",
					"Tout ce que je fais est pour les gens ordinaires.",
					"Je ferais tout pour protéger le temple dans lequel je servais.",
					"Je cherche à préserver un texte sacré que mes ennemis veulent détruire car ils le considèrent hérétique." ],
				[	/* Artiste */
					"Mon instrument est mon bien le plus précieux, et il me rappelle quelqu'un que j'aime.",
					"Quelqu'un a volé mon précieux instrument, et un jour je le récupérerai.",
					"Je veux être connu, et ferais n'importe quoi pour cela.",
					"J'idolâtre le héros d'une vieille histoire et calque mes actions sur les siennes.",
					"Je ferais n'importe quoi pour me prouver que je suis supérieur à mon détesté rival.",
					"Je ferais n'importe quoi pour les membres de mon ancienne troupe." ],
				[	/* Artisan */
					"L'atelier où j'ai appris mon métier est l'endroit le plus important au monde pour moi.",
					"J'ai créé un travail remarquable pour certaines personnes, puis les ai trouvées indignes de le recevoir. Je suis encore à la recherche d'une personne qui le méritera.",
					"J'ai une énorme dette envers ma guilde, car elle a fait de moi ce que je suis aujourd'hui.",
					"Je cherche à être riche pour m'assurer l'amour d'une personne.",
					"Un jour je retournerai à ma guilde et leur prouverai que je suis un bien plus grand artisan qu'eux.",
					"Je vais prendre ma revanche sur les forces maléfiques qui ont détruit mon atelier et anéanti mon gagne-pain." ],
				[	/* Charlatan */
					"J'ai floué la mauvaise personne et ai intérêt à tout faire pour qu'elle ne recroise plus jamais mon chemin ou celui d'un de mes proches.",
					"Je dois tout à mon maître, une horrible personne qui est probablement en train de pourrir en prison.",
					"Dehors, quelque part, j'ai un enfant qui ne me connaît pas. Je cherche à rendre le monde meilleur pour lui/elle.",
					"Je viens d'une famille noble, et un jour je viendrai leur réclamer mes terres et mon titre qu'ils m'ont lâchement dérobés.",
					"Une personne très puissante a tué quelqu'un que j'aimais. Un jour prochain, j'aurai ma revanche.",
					"J'ai escroqué et ruiné une personne qui ne le méritait pas. Je cherche à expier mon erreur, mais je ne pourrai jamais me le pardonner." ],
				[	/* Criminel */
					"Je suis en train de payer une vieille dette que je dois à un généreux bienfaiteur.",
					"Mes gains mal acquis vont soutenir ma famille.",
					"Quelque chose d'important m'a été pris, et je dois le voler de nouveau.",
					"Je vais devenir le plus grand voleur qui n'ait jamais été.",
					"Je suis coupable d'un crime terrible. J'espère pouvoir me racheter.",
					"Quelqu'un que j'aimais est mort à cause d'une erreur que j'ai faite. Cela ne se reproduira plus." ],
				[	/* ermite */
					"Rien n'est plus important que les autres membres de mon ermitage, de mon ordre ou de mon association.",
					"Je me suis reclus pour me cacher de ceux qui pourraient encore être en train de me chasser. Un jour je devrais les affronter.",
					"Je suis toujours en quête de l'illumination. Je la poursuivais dans mon isolement, et elle m'échappe encore.",
					"Je me suis reclus parce que j'aimais quelqu'un que je ne pouvais pas avoir.",
					"Si ma découverte sort à la lumière, elle pourrait détruire le monde.",
					"Mon isolement m'a donné une grande perspective sur un grand mal et je suis le seul à pouvoir le détruire." ],
				[ 	/* sauvageon */
					"Ma famille, mon clan ou ma tribu sont les choses les plus importantes dans ma vie, même lorsqu'ils sont loin de moi.",
					"Insulter la nature indomptée de mes terres c'est m'insulter.",
					"Ma terrible colère s'abattra sur les malfrats qui ont saccagé ma terre.",
					"Je suis le dernier des membres de ma tribu, et il me revient de faire entrer leur nom dans la légende.",
					"J'ai eu d'horribles visions d'un grand désastre imminent et vais tout faire pour l'empêcher.",
					"Il est de mon devoir de faire des enfants pour le salut de ma tribu." ],
				[	/* enfant des rues */
					"Ma ville, ou ma cité, est ma maison, et je me battrai pour la défendre.",
					"Je finance un orphelinat pour éviter que d'autres subissent la même chose que moi.",
					"Je dois ma survie à un autre enfant des rues qui m'a appris à vivre sans abris.",
					"J'ai une dette que je ne pourrai jamais rembourser envers la personne qui m'a prise en pitié.",
					"J'ai échappé à mon sort en volant une personne très importante, et je suis recherché pour cela.",
					"Personne d'autre ne peut endurer les épreuves que j'ai surmontées." ],
				[	/* heros du peuple */
					"J'ai une famille, mais je ne sais pas où ils sont. Un jour, j'espère les revoir.",
					"J'ai travaillé la terre, j'aime la terre, et je vais protéger la terre.",
					"Un noble orgueilleux m'a un jour passé une horrible raclée. Je vais prendre ma revanche sur le premier tyran que je rencontre.",
					"Mes outils sont le symbole de ma vie passée, et je les porte pour ne jamais oublier mes racines.",
					"Je protège ceux qui sont sans défense.",
					"Je souhaite que ma petite amie lorsque j'étais enfant vienne avec moi pour poursuivre mon destin." ],
				[	/* marin */
					"Je reste loyal envers mon premier capitaine, tout passe après lui.",
					"Le navire est le plus important, les équipages et les capitaines vont et viennent.",
					"Je me rappellerai toujours de mon premier navire.",
					"Dans une ville portuaire, j'ai une maîtresse dont les yeux ont failli m'arracher à la mer.",
					"J'ai été trompé sur la part de profits qui me revient de droit, et je vais récupérer mon dû.",
					"Des pirates sans pitié ont tué mon capitaine et les autres membres d'équipage, ont pillé notre navire et m'ont laissé pour mort. La vengeance sera mienne." ],
				[	/* noble */
					"Je ferais face à n'importe quel défi pour gagner l'approbation de ma famille.",
					"L'alliance de ma maison avec une autre famille noble doit être maintenue à tout prix.",
					"Rien n'est plus important que les autres membres de ma famille.",
					"Je suis amoureux de l'héritière d'une famille que ma propre famille méprise.",
					"Ma loyauté envers mon souverain est inébranlable.",
					"Les gens ordinaires doivent me voir comme un héros du peuple." ],
				[	/* sage */
					"Il est de mon devoir de protéger mes élèves.",
					"Je possède un texte ancien qui renferme de terribles secrets qui ne doivent pas tomber entre de mauvaises mains.",
					"Je travaille à préserver une bibliothèque, une université, un scriptorium ou un monastère.",
					"Le travail de ma vie est une série de livres sur un domaine spécifique de connaissance.",
					"J'ai cherché toute ma vie la réponse à une question.",
					"J'ai vendu mon âme pour de la connaissance. J'espère faire de grandes choses et la récupérer en retour." ],
				[	/* soldat */
					"Je voudrais pouvoir encore donner ma vie pour les gens avec qui j'ai servi.",
					"Quelqu'un m'a sauvé la vie sur le champ de bataille. À ce jour, je ne pourrais jamais laisser un ami derrière.",
					"Mon honneur est ma vie.",
					"Je n'oublierai jamais la défaite écrasante que ma compagnie a subie ni les ennemis qui nous l'ont infligée.",
					"Ceux qui se battent à mes côtés sont ceux pour qui cela vaut la peine de mourir.",
					"Je me bats pour ceux qui ne peuvent pas se battre pour eux-mêmes." ],
				[	/* chevalier */
					"Je ferais face à n'importe quel défi pour gagner l'approbation de ma famille.",
					"L'alliance de ma maison avec une autre famille noble doit être maintenue à tout prix.",
					"Rien n'est plus important que les autres membres de ma famille.",
					"Je suis amoureux de l'héritière d'une famille que ma propre famille méprise.",
					"Ma loyauté envers mon souverain est inébranlable.",
					"Les gens ordinaires doivent me voir comme un héros du peuple." ],
				[	/* voyageur */
					"J'ai entendu parler d'un endroit où je veux absolument aller.",
					"Au cours de mes voyages, je suis tombé éperdument amoureux d'une personne, un jour je reviendrai pour conquérir son cœur.",
					"Mon périple est une tâche initiatique que ma communauté m'a dictée. Lorsque je serais arrivé au bout du voyage, je reviendrai chez moi.",
					"J'ai un animal de compagnie, un fidèle compagnon de voyage que je ne laisserai tomber pour rien au monde.",
					"J'ai fui l'endroit où j'ai grandi et je n'ose plus y retourner.",
					"Chaque pas que je fais m'éloigne d'un destin qui m'a été prédit." ],
				[	/* captif */
					"J'ai réussi à m'échapper, mais j'ai laissé derrière moi des compagnons de fortune que je me dois de délivrer.",
					"Si j'ai été capturé, c'est parce qu'on m'a trahi. Le coupable doit payer.",
					"Le chef de la tribu a été ignoble avec moi. Je le retrouverai.",
					"Captif mais pas mal traité, j'ai appris à comprendre ces créatures.",
					"Pour avoir été absent si longtemps, j'ai tout perdu professionnellement. Je dois me reconstruire.",
					"Ma famille m'a cru mort et a déménagé. Il me faut les retrouver." ],
				[	/* idiot */
					"Je n'ai quasiment aucun lien affectif, sauf pour un de mes proches pour qui je donnerais ma vie.",
					"On me recherche car je garde un secret dangereux, sans en avoir réellement conscience.",
					"Une créature fantastique m'a rendu mes capacités intellectuelles mais je dois accomplir une mission pour elle en retour.",
					"On m'a conté des légendes sur des objets merveilleux et j'ai tout quitté pour aller les retrouver.",
					"J'ai été accusé d'un crime que je n'ai pas commis et banni de mon village. Je veux prouver mon innocence.",
					"J'ai trouvé un objet intelligent qui me guide dans mes aventures. « Mon précieux... »" ],
				[	/* chasseur urbain */
					"Je suis en train de payer une vieille dette que je dois à un généreux bienfaiteur.",
					"Mes gains mal acquis vont soutenir ma famille.",
					"Quelque chose d'important m'a été pris, et je dois le voler de nouveau.",
					"Je vais devenir le plus grand voleur qui n'ait jamais été.",
					"Je suis coupable d'un crime terrible. J'espère pouvoir me racheter.",
					"Quelqu'un que j'aimais est mort à cause d'une erreur que j'ai faite. Cela ne se reproduira plus." ],
				[	/* vétéran */
					"Je voudrais pouvoir encore donner ma vie pour les gens avec qui j'ai servi.",
					"Quelqu'un m'a sauvé la vie sur le champ de bataille. À ce jour, je ne pourrais jamais laisser un ami derrière.",
					"Mon honneur est ma vie.",
					"Je n'oublierai jamais la défaite écrasante que ma compagnie a subie ni les ennemis qui nous l'ont infligée.",
					"Ceux qui se battent à mes côtés sont ceux pour qui cela vaut la peine de mourir.",
					"Je me bats pour ceux qui ne peuvent pas se battre pour eux-mêmes." ],
];

var DEFAUTS = [	[ 	/* Acolyte */
					"Je juge sévèrement les autres, en partie parce que je suis encore plus sévère envers moi-même.",
					"J'ai trop confiance en ceux qui exercent le pouvoir au sein de la hiérarchie de mon temple.",
					"Ma piété me conduit parfois à faire confiance aveuglément à ceux qui professent la foi de mon dieu.",
					"Je suis inflexible dans ma pensée.",
					"Je suis méfiant envers les étrangers et m'attends au pire de leur part.",
					"Une fois que j'ai un but, je deviens obsédé par celui-ci, au détriment du reste de ma vie." ],
				[	/* Artiste */
					"Je ferais n'importe quoi pour gagner gloire et notoriété.",
					"Je suis sans défense devant un joli minois.",
					"Un scandale m'empêche de retourner chez moi. Ce genre de désagrément semble me suivre de partout.",
					"J'ai un jour caricaturé un noble, lequel cherche encore à voir ma tête au bout d'une pique. C'était une erreur que je vais probablement répéter.",
					"J'ai des difficultés à garder mes vrais sentiments pour moi. Ma langue acérée me cause beaucoup de problèmes.",
					"En dépit de mes efforts, mes amis ont peu confiance en moi." ],
				[	/* Artisan */
					"Je ferais n'importe quoi pour mettre la main sur quelque chose de rare ou d'inestimable.",
					"Je me persuade très vite que les gens cherchent à me rouler dans la farine.",
					"Personne ne doit savoir que j'ai un jour dérobé l'or des coffres d'une guilde.",
					"Je ne suis jamais satisfait de ce que j'ai, je veux toujours plus.",
					"Je tuerai pour obtenir un titre de noblesse.",
					"Je suis horriblement jaloux de tous ceux qui peuvent surpasser mes créations. Partout où je vais, je suis entouré de rivaux." ],
				[	/* Charlatan */
					"Je ne peux pas résister à un joli minois.",
					"J'ai toujours des dettes. Je dépense mon argent sale dans des produits de luxe plus rapidement que je ne le gagne.",
					"Je suis persuadé que jamais personne ne pourra me rouler de la manière dont je roule les autres.",
					"Je suis trop gourmand lorsqu'il s'agit de profit. Je ne peux pas m'empêcher de prendre des risques lorsque de l'argent est en jeu.",
					"Je ne peux pas m'empêcher d'escroquer ceux qui sont plus puissants que moi.",
					"Je déteste l'admettre et je vais me détester pour cela, mais je prendrai mes jambes à mon cou et sauverai avant tout ma vie si la situation devient critique." ],
				[	/* Criminel */
					"Quand je vois quelque chose de précieux, je ne pense qu'à une chose : comment m'en emparer.",
					"Lorsque je suis confronté à un choix entre l'argent et mes amis, je choisis généralement l'argent.",
					"S'il y a un plan, je vais l'oublier. Si je ne l'oublie pas, je l'ignore.",
					"Il y a quelque chose qui me trahit quand je mens.",
					"Je tourne le dos et m'enfuis en courant quand les choses vont mal.",
					"Une personne innocente est en prison pour un crime que j'ai commis. Et je n'ai pas de problème avec cela." ],
				[	/* ermite */
					"Maintenant que je suis revenu à la civilisation, j'apprécie un peu trop ses plaisirs.",
					"Je nourris de sombres pensées sanguinaires que mon isolement et la méditation n'ont pas réussi à étouffer.",
					"Je suis dogmatique dans mes pensées et ma philosophie.",
					"Je laisse mon besoin de gagner les discussions éclipser l'amitié et l'harmonie.",
					"Je suis prêt à prendre trop de risques pour découvrir un peu de connaissances perdues.",
					"J'aime garder des secrets et je ne les partage avec personne." ],
				[ 	/* sauvageon */
					"Je ne suis pas du tout résistant à la bière, au vin et autres boissons alcoolisées.",
					"Il n'y a pas de place pour la prudence dans une vie pleinement vécue.",
					"Je me rappelle de toutes les injures que j'ai reçues, et nourris une haine silencieuse envers tous ceux qui m'ont fait du tort.",
					"Je mets du temps à faire confiance aux membres d'autres races, tribus ou sociétés.",
					"La violence est ma réponse à presque tous les défis.",
					"N'espérez pas que je sauve ceux qui ne peuvent pas se sauver eux-même. C'est la loi de la nature, les forts survivent et les faibles périssent." ],
				[	/* enfant des rues */
					"Si je suis en infériorité numérique, je fuis le combat.",
					"L'or me paraît être une énorme quantité d'argent, et je ferai n'importe quoi pour en obtenir toujours plus.",
					"Je ne ferai jamais pleinement confiance à quelqu'un d'autre qu'à moi-même.",
					"Je préfère tuer quelqu'un dans son sommeil plutôt que de combattre à la loyale.",
					"Ce n'est pas du vol si j'en ai plus besoin que quelqu'un d'autre.",
					"Les gens qui ne peuvent pas prendre soin d'eux-même n'ont que ce qu'ils méritent." ],
				[	/* heros du peuple */
					"Le tyran qui gouverne ma terre ne reculera devant rien pour me voir mort.",
					"Je suis convaincu de l'importance de mon destin, et aveugle devant mes lacunes et les risques d'échec.",
					"Les gens qui m'ont connu plus jeune connaissent mon secret honteux. Pour cette raison je ne pourrais jamais revenir chez moi.",
					"J'ai un faible pour les vices de la ville, en particulier pour les alcools forts.",
					"Secrètement, je crois que les choses iraient mieux si j'étais un tyran gouvernant ce territoire.",
					"J'ai du mal à faire confiance à mes alliés." ],
				[	/* marin */
					"Je suis les ordres, même si je pense qu'ils sont mauvais.",
					"Je dirais n'importe quoi pour éviter d'avoir du travail supplémentaire.",
					"Lorsque quelqu'un met en doute mon courage, je ne recule devant rien pour le faire changer d'avis, même si les situations sont extrêmement périlleuses.",
					"Lorsque je commence à boire, il est difficile de me faire arrêter.",
					"Je n'y peux rien mais les poches des autres perdent leurs pièces et leurs babioles lorsque je passe dans le coin.",
					"Mon orgueil me mènera probablement à ma perte." ],
				[	/* noble */
					"Je crois secrètement que tout le monde est au-dessous de moi.",
					"Je cache un secret vraiment scandaleux qui pourrait ruiner la réputation de ma famille pour toujours.",
					"J'entends trop souvent des insultes et des menaces à peine voilées quand on s'adresse à moi, et je suis prompt à la colère.",
					"J'ai un désir insatiable de plaisirs charnels.",
					"En fait, le monde tourne autour de moi.",
					"Par mes paroles et mes actions, je fais honte à ma famille." ],
				[	/* sage */
					"Je suis facilement distrait par la promesse d'information.",
					"La plupart des gens crient et courent quand ils voient un démon. Moi je m'arrête et je prends des notes sur son anatomie.",
					"Décrypter un mystère ancien vaut le prix d'une civilisation.",
					"Je privilégie les solutions compliquées aux dépens des solutions faciles.",
					"Je parle sans vraiment penser mes mots, insultant invariablement les autres.",
					"Je ne peux pas garder un secret pour sauver ma vie, ou n'importe qui d'autre." ],
				[	/* soldat */
					"L'ennemi monstrueux que nous avons affronté dans la bataille me fait encore frémir de peur.",
					"J'ai peu de respect pour celui qui n'est pas un réel guerrier.",
					"J'ai commis une terrible erreur durant une bataille qui a coûté la vie à de nombreuses personnes et je ferais n'importe quoi pour garder cette erreur secrète.",
					"Ma haine pour mes ennemis est aveugle et irraisonnée.",
					"J'obéis à la loi, même si elle provoque la misère.",
					"Je préfère manger mon armure plutôt qu'admettre que je me suis trompé." ],
				[	/* chevalier */
					"Je crois secrètement que tout le monde est au-dessous de moi.",
					"Je cache un secret vraiment scandaleux qui pourrait ruiner la réputation de ma famille pour toujours.",
					"J'entends trop souvent des insultes et des menaces à peine voilées quand on s'adresse à moi, et je suis prompt à la colère.",
					"J'ai un désir insatiable de plaisirs charnels.",
					"En fait, le monde tourne autour de moi.",
					"Par mes paroles et mes actions, je fais honte à ma famille." ],
				[	/* voyageur */
					"Voyager est tout ce qui compte pour moi, jamais je ne m'installerai quelque part.",
					"Je ne suis pas tranquille tant que je n'ai pas marché pendant au moins une heure, quitte à faire les cent pas.",
					"Je finis toujours par mélanger les coutumes de différents peuples et par commettre des faux-pas.",
					"Je me suis fait un ennemi puissant dans un pays lointain et j'espère qu'il ne découvrira jamais où je me trouve.",
					"Je reste d'une grande naïveté et crois qu'il y a du bon en absolument tout le monde.",
					"Je ne voyage pas par plaisir, je fuis quelque chose de terrible qui me poursuit sans relâche." ],
				[	/* captif */
					"À la vue de ces créatures je ne me contrôle plus.",
					"Je ne supporte plus qu'on me donne des ordres.",
					"Je suis claustrophobe, j'ai peur d'être enfermé.",
					"J'ai tout perdu, boulot et famille. Je n'ai plus rien à perdre.",
					"Je ne supporte plus qu'on me touche.",
					"J'ai du mal à accorder ma confiance." ],
				[	/* idiot */
					"Je touche toujours à tout, surtout à ce qu'on m'interdit d'approcher.",
					"Je suis un menteur compulsif, créant régulièrement la discorde et les problèmes.",
					"Je n'ai aucune conscience du danger... et n'ai donc peur de rien.",
					"J'ai souvent faim. Et quand j'ai faim, je ne pense à rien d'autre qu'à manger.",
					"Quand je parle à quelqu'un, je finis toujours par l'insulter ouvertement.",
					"Quand je suis content, je vomis." ],
				[	/* chasseur urbain */
					"Quand je vois quelque chose de précieux, je ne pense qu'à une chose : comment m'en emparer.",
					"Lorsque je suis confronté à un choix entre l'argent et mes amis, je choisis généralement l'argent.",
					"S'il y a un plan, je vais l'oublier. Si je ne l'oublie pas, je l'ignore.",
					"Il y a quelque chose qui me trahit quand je mens.",
					"Je tourne le dos et m'enfuis en courant quand les choses vont mal.",
					"Une personne innocente est en prison pour un crime que j'ai commis. Et je n'ai pas de problème avec cela." ],
				[	/* vétéran */
					"L'ennemi monstrueux que nous avons affronté dans la bataille me fait encore frémir de peur.",
					"J'ai peu de respect pour celui qui n'est pas un réel guerrier.",
					"J'ai commis une terrible erreur durant une bataille qui a coûté la vie à de nombreuses personnes et je ferais n'importe quoi pour garder cette erreur secrète.",
					"Ma haine pour mes ennemis est aveugle et irraisonnée.",
					"J'obéis à la loi, même si elle provoque la misère.",
					"Je préfère manger mon armure plutôt qu'admettre que je me suis trompé." ],
];

var PACK = [ "<h4>Pack (a) de barbare</h4><ul><li>Hache à deux mains</li><li>2 hachettes</li><li>4 javelines</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (b) de barbare</h4><ul><li>1 arme de guerre de corps à corps</li><li>1 arme courante</li><li>4 javelines</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de barde</h4><ul><li>Armure de cuir</li><li>Rapière</li><li>Dague</li><li>Luth</li><li>Sac de diplomate</li></ul>",
			 "<h4>Pack (b) de barde</h4><ul><li>Armure de cuir</li><li>Épée longue</li><li>Dague</li><li>Instrument de musique</li><li>Sac d'artiste</li></ul>",
			 "<h4>Pack (a) de clerc</h4><ul><li>Armure d'écailles</li><li>Bouclier</li><li>Masse d'armes</li><li>Arbalète légère</li><li>Symbole sacré</li><li>Sac d'ecclésiastique</li></ul>",
			 "<h4>Pack (b) de clerc</h4><ul><li>Armure de cuir</li><li>Bouclier</li><li>Marteau de guerre</li><li>1 arme courante</li><li>Symbole sacré</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de druide</h4><ul><li>Armure de cuir</li><li>Bouclier</li><li>Cimeterre</li><li>Focaliseur druidique</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (b) de druide</h4><ul><li>Armure de cuir</li><li>1 arme courante</li><li>Arme courante de corps à corps</li><li>Focaliseur druidique</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) d'ensorceleur</h4><ul><li>Arbalète légère et 20 carreaux</li><li>2 dagues</li><li>Sacoche à composantes</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (b) d'ensorceleur</h4><ul><li>1 arme courante</li><li>2 dagues</li><li>Focaliseur arcanique</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de guerrier</h4><ul><li>Cotte de mailles</li><li>Bouclier</li><li>1 arme de guerre</li><li>Arbalète légère</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (b) de guerrier</h4><ul><li>Armure de cuir</li><li>2 armes de guerre</li><li>2 hachettes</li><li>Arc long</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de magicien</h4><ul><li>Bâton</li><li>Grimoire</li><li>Sacoche à composantes</li><li>Sac d'érudit</li></ul>",
			 "<h4>Pack (b) de magicien</h4><ul><li>Dague</li><li>Grimoire</li><li>Focaliseur arcanique</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de moine</h4><ul><li>Épée courte</li><li>10 fléchettes</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (b) de moine</h4><ul><li>1 arme courante</li><li>10 fléchettes</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de paladin</h4><ul><li>Cotte de mailles</li><li>Bouclier</li><li>1 arme de guerre</li><li>5 javelines</li><li>Symbole sacré</li><li>Sac d'ecclésiastique</li></ul>",
			 "<h4>Pack (b) de paladin</h4><ul><li>Cotte de mailles</li><li>2 armes de guerre</li><li>1 arme courante de corps à corps</li><li>Symbole sacré</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de rôdeur</h4><ul><li>Armure d'écailles</li><li>2 épées courtes</li><li>Arc long</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (b) de rôdeur</h4><ul><li>Armure de cuir</li><li>2 armes courantes de corps à corps</li><li>Arc long</li><li>Sac d'explorateur</li></ul>",
			 "<h4>Pack (a) de roublard</h4><ul><li>Armure de cuir</li><li>Rapière</li><li>Arc court</li><li>2 dagues</li><li>Outils de voleur</li><li>Sac de cambrioleur</li></ul>",
			 "<h4>Pack (b) de roublard</h4><ul><li>Armure de cuir</li><li>2 épées courtes</li><li>2 dagues</li><li>Outils de voleur</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (a) d'occultiste</h4><ul><li>Armure de cuir</li><li>2 dagues</li><li>Arbalète légère et 20 carreaux</li><li>1 arme courante</li><li>Sacoche à composantes</li><li>Sac d'érudit</li></ul>",
			 "<h4>Pack (b) d'occultiste</h4><ul><li>Armure de cuir</li><li>2 dagues</li><li>2 armes courantes</li></li><li>Focaliseur arcanique</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (a) d'artificier</h4><ul><li>Armure de cuir clouté</li><li>2 armes courantes</li><li>Arbalète légère et 20 carreaux</li><li>Outils de voleur</li><li>Sac d'exploration souterraine</li></ul>",
			 "<h4>Pack (b) d'artificier</h4><ul><li>armure d'écailles</li><li>2 armes courantes</li><li>Arbalète légère et 20 carreaux</li></li><li>Outils de voleur</li><li>Sac d'exploration souterraine</li></ul>"
];

var ARMURE = [" ",
	"<h4>Matelassée</h4>			<p>Armure légère<br />CA : 11 + modificateur de Dextérité<br />Désavantage en discrétion</p>",
	"<h4>Cuir</h4> 					<p>Armure légère<br />CA : 11 + modificateur de Dextérité</p>",
	"<h4>Cuir clouté</h4>			<p>Armure légère<br />CA : 12 + modificateur de Dextérité</p>",
	"<h4>Peau</h4>			 		<p>Armure intermédiaire<br />CA : 12 + modificateur de Dextérité (max 2)</p>",
	"<h4>Chemise de mailles</h4> 	<p>Armure intermédiaire<br />CA : 13 + modificateur de Dextérité (max 2)</p>",
	"<h4>Écailles</h4>			 	<p>Armure intermédiaire<br />CA : 14 + modificateur de Dextérité (max 2)<br />Désavantage en discrétion</p>",
	"<h4>Cuirasse</h4>				<p>Armure intermédiaire<br />CA : 14 + modificateur de Dextérité (max 2)</p>",
	"<h4>Demi-plate</h4>	 		<p>Armure intermédiaire<br />CA : 15 + modificateur de Dextérité (max 2)<br />Désavantage en discrétion</p>",

	"<h4>Broigne</h4> 				<p>Armure lourde<br />CA : 14<br />Désavantage en discrétion</p>",
	"<h4>Cotte de mailles</h4> 		<p>Armure lourde<br />CA : 16<br />Désavantage en discrétion<br />Vitesse -3 m si Force < 13</p>",
	"<h4>Clibanion</h4> 			<p>Armure lourde<br />CA : 17<br />Désavantage en discrétion<br />Vitesse -3 m si Force < 15</p>",
	"<h4>Harnois</h4> 				<p>Armure lourde<br />CA : 18<br />Désavantage en discrétion<br />Vitesse -3 m si Force < 15</p>"
];

var BOUCLIER = [ " ",
	"<h4>Bouclier</h4> 				<p>Bouclier<br />CA : +2</p>"
];

var ARME = [ " ",
	"<h4>Mains nues</h4>",
	"<h4>Bâton</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d6 (contondant)<br />Polyvalente (1d8)</p>",
	"<h4>Dague</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d4 (perforant)<br />Finesse, légère, lancer (portée 6/18)</p>",
	"<h4>Gourdin</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d4 (contondant)<br />Légère</p>",
	"<h4>Hachette</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d6 (tranchant)<br />Légère, lancer (portée 6/18)</p>",
	"<h4>Javeline</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d6 (perforant)<br />Lancer (portée 9/36)</p>",
	"<h4>Lance</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d6 (perforant)<br />Lancer (portée 6/18), polyvalente (1d8)</p>",
	"<h4>Marteau léger</h4> 		<p>Arme courante de corps à corps<br />Dégâts : 1d4 (contondant)<br />Légère, lancer (portée 6/18)</p>",
	"<h4>Masse d'armes</h4> 		<p>Arme courante de corps à corps<br />Dégâts : 1d6 (contondant)</p>",
	"<h4>Massue</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d8 (contondant)<br />À deux mains</p>",
	"<h4>Serpe</h4> 				<p>Arme courante de corps à corps<br />Dégâts : 1d4 (tranchant)<br />Légère</p>",

	"<h4>Arbalète légère</h4> 		<p>Arme courante à distance<br />Dégâts : 1d8 (perforant)<br />Munitions (portée 24/96), chargement, à deux mains</p>",
	"<h4>Arc court</h4> 			<p>Arme courante à distance<br />Dégâts : 1d6 (perforant)<br />Munitions (portée 24/96), à deux mains</p>",
	"<h4>Fléchette</h4> 			<p>Arme courante à distance<br />Dégâts : 1d4 (perforant)<br />Finesse, lancer (portée 9/36)</p>",
	"<h4>Fronde</h4> 				<p>Arme courante à distance<br />Dégâts : 1d4 (contondant)<br />Munitions (portée 9/36)</p>",

	"<h4>Cimeterre</h4> 			<p>Arme de guerre de corps à corps<br />Dégâts : 1d6 (tranchant)<br />Finesse, légère</p>",
	"<h4>Coutille</h4> 				<p>Arme de guerre de corps à corps<br />Dégâts : 1d10 (tranchant)<br />Lourde, allonge, à deux mains</p>",
	"<h4>Épée à deux mains</h4>		<p>Arme de guerre de corps à corps<br />Dégâts : 2d6 (tranchant)<br />Lourde, à deux mains</p>",
	"<h4>Épée courte</h4> 			<p>Arme de guerre de corps à corps<br />Dégâts : 1d6 (perforant)<br />Finesse, légère</p>",
	"<h4>Épée longue</h4> 			<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (tranchant)<br />Polyvalente (1d10)</p>",
	"<h4>Fléau d'armes</h4> 		<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (contondant)</p>",
	"<h4>Fouet</h4> 				<p>Arme de guerre de corps à corps<br />Dégâts : 1d4 (tranchant<br />Finesse, allonge</p>",
	"<h4>Hache à deux mains</h4> 	<p>Arme de guerre de corps à corps<br />Dégâts : 1d12 (tranchant)<br />Lourde, à deux mains</p>",
	"<h4>Hache d'armes</h4> 		<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (tranchant)<br />Polyvalente (1d10)</p>",
	"<h4>Hallebarde</h4> 			<p>Arme de guerre de corps à corps<br />Dégâts : 1d10 (tranchant)<br />Lourde, allonge, à deux mains</p>",

	"<h4>Lance d'arçon</h4> 		<p>Arme de guerre de corps à corps<br />Dégâts : 1d12 (perforant)<br />Allonge, spécial</p>",
	"<h4>Maillet</h4> 				<p>Arme de guerre de corps à corps<br />Dégâts : 2d6 (contondant)<br />Lourde, à deux mains</p>",
	"<h4>Marteau de guerre</h4>		<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (contondant)<br />Polyvalente (1d10)</p>",
	"<h4>Morgenstern</h4> 			<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (perforant)</p>",
	"<h4>Pic de guerre</h4> 		<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (perforant)</p>",
	"<h4>Pique</h4> 				<p>Arme de guerre de corps à corps<br />Dégâts : 1d10 (perforant)<br />Lourde, allonge, à deux mains</p>",
	"<h4>Rapière</h4> 				<p>Arme de guerre de corps à corps<br />Dégâts : 1d8 (perforant)<br />Finesse</p>",
	"<h4>Trident</h4> 				<p>Arme de guerre de corps à corps<br />Dégâts : 1d6 (perforant)<br />Lancer (portée 6/18), polyvalente (1d8)</p>",

	"<h4>Arbalète de poing</h4>		<p>Arme de guerre à distance<br />Dégâts : 1d6 (perforant)<br />Munitions (portée 9/36), légère, chargement</p>",
	"<h4>Arbalète lourde</h4>		<p>Arme de guerre à distance<br />Dégâts : 1d10 (perforant)<br />Munitions (portée 30/120), lourde, chargement, à deux mains</p>",
	"<h4>Arc long</h4> 				<p>Arme de guerre à distance<br />Dégâts : 1d8 (perforant)<br />Munitions (portée 45/180), lourde, à deux mains</p>",
	"<h4>Filet</h4> 				<p>Arme de guerre à distance<br />Dégâts : -<br />Spécial, lancer (portée 1,50/4,50)</p>",
	"<h4>Sarbacane</h4> 			<p>Arme de guerre à distance<br />Dégâts : 1 (perforant)<br />Munitions (portée 7,50/30), chargement</p>"
];

var TABXP	= [0,0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000,405000];
var XPKO	= "<h4>Expérience</h4>Un personnage de votre niveau devrait avoir un nombre de points d'expérience compris entre ";
var XPET	= " et ";
var XPOK	= "<h4>Expérience</h4>Vos points d'expérience sont corrects pour un personnage de votre niveau !";
var ENNHUM	= "<h4>Ennemi juré</h4><p>Spécifiez 2 races humanoïdes (comme gnolls et orcs) comme ennemis favoris.</p>";
var EXTRAIT = "<h4>Exemples de traits</h4><h5>Cliquez sur une option pour la sélectionner</h5>";
var EXIDEAL = "<h4>Exemples d'idéaux</h4><h5>Cliquez sur une option pour la sélectionner</h5>";
var EXLIEN	= "<h4>Exemples de liens</h4><h5>Cliquez sur une option pour la sélectionner</h5>";
var EXDEFAUT= "<h4>Exemples de défauts</h4><h5>Cliquez sur une option pour la sélectionner</h5>";
var SPECIAL = "<h4>Spécialité de l'historique</h4><h5>Cliquez sur une option pour la sélectionner</h5>";
